# Generated by Django 4.2.4 on 2025-01-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line2',
            new_name='jibunAddress',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line1',
            new_name='roadAddress',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
