# Generated by Django 4.2.4 on 2025-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_address_line2_address_jibunaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='refund_bank',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='refund_account_number',
            new_name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mileage',
        ),
        migrations.AlterField(
            model_name='address',
            name='jibunAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='지번주소'),
        ),
        migrations.AlterField(
            model_name='address',
            name='roadAddress',
            field=models.CharField(max_length=255, verbose_name='도로명주소'),
        ),
    ]
