# Generated by Django 4.2.4 on 2025-01-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_refund_bank_customuser_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detailAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='address',
            name='extraAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='참고주소'),
        ),
    ]
