# Generated by Django 4.2.4 on 2025-03-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_bankaccount_customuser_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_agree',
            field=models.BooleanField(default=False, verbose_name='마케팅 수신 동의'),
        ),
    ]
