# Generated by Django 4.2.20 on 2025-05-06 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bankAccount',
        ),
        migrations.CreateModel(
            name='RefundBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50, verbose_name='은행명')),
                ('account_number', models.CharField(max_length=30, verbose_name='계좌번호')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_account', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='변동 마일리지')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='쿠폰 코드')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='할인 금액')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('expiration_date', models.DateField(verbose_name='유효기간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
    ]
