FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential redis-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt ./ 
RUN pip install -r requirements.txt

COPY wait-for-redis.sh /wait-for-redis.sh
RUN chmod +x /wait-for-redis.sh

RUN useradd -m celeryuser
USER celeryuser

CMD ["sh", "-c", "/wait-for-redis.sh redis celery -A lepond worker --loglevel=info"]
