# version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lepond_network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck: 
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lepond_network

      
  django:
    build:
      context: .
      dockerfile: Dockerfile.django  
    container_name: django_app
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy 
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - lepond_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      django:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - lepond_network

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery_worker
    container_name: celery_worker
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy 
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - lepond_network

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery_beat
    container_name: celery_beat
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy  
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - lepond_network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    command: >
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL}
      --agree-tos --no-eff-email
      -d lepond.kr -d www.lepond.kr
        networks:
          - lepond_network

networks:
  lepond_network:
    driver: bridge

volumes:
  mariadb_data: