# Generated by Django 4.2.4 on 2025-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='category',
            field=models.CharField(choices=[('shipping', '배송 문의'), ('payment', '결제, 환불 문의'), ('product', '제품 문의'), ('other', 'etc')], max_length=20, verbose_name='카테고리'),
        ),
    ]
