# Generated by Django 4.2.4 on 2025-03-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('community', '0002_alter_qna_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qnas', to='shop.product', verbose_name='관련 제품'),
        ),
    ]
