# Generated by Django 4.2.20 on 2025-04-12 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_product_created_at'),
        ('community', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='리뷰 제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='리뷰 내용')),
                ('rating', models.PositiveIntegerField(verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review_images/', verbose_name='리뷰 이미지')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='이미지 설명')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='community.review', verbose_name='리뷰')),
            ],
        ),
    ]
