# Generated by Django 4.2.20 on 2025-04-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_review_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.review', verbose_name='리뷰')),
            ],
            options={
                'verbose_name': '리뷰 댓글',
                'verbose_name_plural': '리뷰 댓글 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
