# Generated by Django 4.2.4 on 2024-12-18 07:32

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='이미지 제목')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='main_images/', verbose_name='메인 이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
            ],
        ),
    ]
