# Generated by Django 4.2.4 on 2024-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='타이틀')),
                ('content', models.CharField(max_length=255, verbose_name='하단 노출 문구 내용')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
            ],
        ),
    ]
