# Generated by Django 4.2.4 on 2025-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='타이틀')),
                ('content', models.CharField(max_length=500, verbose_name='정책 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100, verbose_name='타이틀'),
        ),
    ]
