# Generated by Django 4.2.4 on 2025-03-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_policy_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='타이틀')),
                ('content', models.CharField(max_length=500, verbose_name='동의 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 시간')),
            ],
        ),
    ]
