# Generated by Django 4.2.4 on 2024-12-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='세션 키')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트일')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='제품명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('mileage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='마일리지 (%)')),
                ('status', models.CharField(choices=[('in_stock', '재고 있음'), ('out_of_stock', '품절'), ('pre_order', '예약 주문')], default='in_stock', max_length=20, verbose_name='제품 상태')),
                ('introduce', models.CharField(max_length=255, verbose_name='상세 설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_thumbnails/', verbose_name='썸네일')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='제품 이미지')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='이미지 설명')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='제품')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caution', models.TextField(blank=True, verbose_name='주의사항')),
                ('material', models.CharField(max_length=255, verbose_name='소재')),
                ('size_guide', models.TextField(blank=True, verbose_name='사이즈 가이드')),
                ('instruction', models.TextField(blank=True, verbose_name='알림')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.product', verbose_name='제품')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='색깔')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.product', verbose_name='제품')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='장바구니')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='제품')),
                ('selected_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcolor', verbose_name='선택한 색깔')),
            ],
        ),
    ]
