# Generated by Django 4.2.20 on 2025-04-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcategory_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
        ),
    ]
