# Generated by Django 4.2.20 on 2025-04-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
